language: r

r:
    - bioc-release

sudo: false
cache:  
    - packages
    - data/shoemaker2015

install: source .build_tools/travis/install.sh
script: source .build_tools/travis/test_script.sh
after_success: source .build_tools/travis/after_success.sh
