sudo: required
services:
    - docker

before_install:
  - docker pull nellev/rbio
  - docker run -d -p 127.0.0.1:80:4567 nellev/rbio /bin/sh -c "cd ~; "
  - docker ps -a

script: source .build_tools/travis/test_script.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: scripts/reports
  on:
    branch: master
