language: r
dist: xenial
sudo: True

r:
    - bioc-release

sudo: false
cache: packages

before_install:
    - sudo apt-get update
    - sudo apt-get install -y pandoc
    - sudo apt-get install -y texlive-base
    - sudo apt-get install -y texlive-xetex

install: source .build_tools/travis/install.sh
script: source .build_tools/travis/test_script.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: scripts/reports
  on:
    branch: master
