
install.packages("devtools")
install.packages("ggfortify")
install.packages("kableExtra")
install.packages("testthat")
install.packages("viridis")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("roxygen2")
install.packages("ClusteR")
install.packages("splines")
install.packages("NMF")
install.packages("ggfortify")
install.packages("reshape2")

source("https://bioconductor.org/biocLite.R")
biocLite("genefilter")
biocLite("limma")
biocLite("edgeR")
biocLite("edge")
biocLite("EDASeq")
biocLite("topGO")
biocLite("Biobase")
biocLite("MASS")
biocLite("biomaRt")
biocLite("KEGGprofile")


